quests:
  - killmob:
    - 1:
      - 450
      - 350
    - 2:
      - 750
      - 950
    - 3:
      - 1250
      - 1750
  - breakBlock:
    - 1:
      - 4050
      - 3500
    - 2:
      - 7500
      - 9500
    - 3:
      - 12500
      - 17500
