quests:
  killmob:
    id: 0
    - 450
    - 350
    - 750
    - 950
    - 1250
    - 1750
  breakBlock:
    - 4500
    - 3500
    - 7500
    - 9500
    - 12500
    - 17500


killmob: 50*j (j le jour)


0:
  name: killmob;
  
